### ISSUE TITLE
Show a biometric authentication dialog

### ISSUE THREAD

**Issue by Abhay-cloud** [Abhay-cloud/Fixed-Deposit-Tracker#4]

**Comment by kuldeepbairwa** [comment]
hey abhay can you assign this issue to me

**Comment by Abhay-cloud** [comment]
Hello @kuldeepbairwa,
I want to set up a biometric authentication dialog that appears when the user opens the app. This should be done in the MainActivity. If authentication fails, the app should close. I've already added the necessary biometric authentication dependencies.

Are you ready to work on this? Please make sure to follow good practices.

**Comment by kuldeepbairwa** [comment]
Yeah sure @Abhay-cloud i'll make sure to follow best practices

**Comment by Abhay-cloud** [comment]
Great! I’ve assigned you the issue.
